language: python
python:
  - "3.7"
install:
  - "pip install flake8 pytest ibm-cos-sdk"
  - "pip install ." 

before_script:
  - "flake8 ."
  - "python tests/cleanup.py"

script:
  - pytest tests/cases/*
